FROM khipu/openjdk17-alpine AS builder

WORKDIR /app

RUN apk add --no-cache maven

COPY ./public-data /app/public-data
COPY ./search-engine /app/search-engine
COPY ./storage-service /app/storage-service
COPY ./account-service /app/account-service

WORKDIR /app/public-data
RUN mvn clean install

WORKDIR /app/search-engine
RUN mvn clean install

WORKDIR /app/storage-service
RUN mvn clean install

WORKDIR /app/account-service
RUN mvn clean package -Dmaven.test.skip

FROM khipu/openjdk17-alpine

WORKDIR /app

COPY --from=builder /app/account-service/main/target/account.jar .

CMD ["java", "-jar", "/app/account.jar"]
