BEGIN;
SET CONSTRAINTS ALL DEFERRED;
insert into dialogs (is_deleted, last_message_id) values (false, 45);
insert into dialogs (is_deleted, last_message_id) values (false, 105);
insert into dialogs (is_deleted, last_message_id) values (false, 165);
insert into dialogs (is_deleted, last_message_id) values (false, 225);

insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '17.1.2023', 1, 2, '11-050 - Library Equipment', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '8.2.2022', 1, 2, '2-782 - Brick Pavers', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '8.11.2022', 1, 2, '1-515 - Temporary Lighting', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '15.3.2022', 1, 2, '15-100 - Plumbing', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '22.2.2023', 1, 2, '10-300 - Fireplaces and Stoves', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '5.4.2022', 1, 2, '15 - Mechanical', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '19.7.2022', 1, 2, '3-000 - General', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '23.2.2023', 1, 2, '12-600 - Multiple Seating', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '3.4.2022', 1, 2, '3-350 - Concrete Finishing', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '11.8.2022', 1, 2, '2-813 - Lawn Sprinkling and Irrigation', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '23.2.2023', 1, 2, '4-900 - Masonry Restoration and Cleaning', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '14.1.2022', 1, 2, '14-800 - Scaffolding', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '17.2.2022', 1, 2, '2-780 - Clay Unit Pavers', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '13.9.2022', 1, 2, '1-011 - Project Engineer', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '3.8.2022', 1, 2, '13-110 - Cathodic Protection', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '10.1.2022', 1, 2, '2-820 - Fences and Gates', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '24.3.2023', 1, 2, '17-020 - Insurance', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '10.1.2023', 1, 2, '12-400 - Furnishings and Accessories', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '22.1.2022', 1, 2, '2-370 - Erosion and Sedimentation Control', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '30.1.2023', 1, 2, '10-300 - Fireplaces and Stoves', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '7.5.2022', 1, 2, '16-400 - Low-Voltage Distribution', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '23.5.2022', 1, 2, '2-250 - Shoring and Underpinning', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '1.2.2022', 1, 2, '2-821 - Chain Link Fences', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '23.1.2022', 1, 2, '1-530 - Temporary Construction', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '26.1.2023', 1, 2, '15-500 - Heat-Generation Equipment', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '22.8.2022', 1, 2, '11 - Equipment', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '31.8.2022', 1, 2, '15-100 - Plumbing', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '23.12.2022', 1, 2, '7-300 - Shingles, Roof Tiles, and Roof Coverings', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '6.2.2023', 1, 2, '1-740 - Cleaning', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '27.2.2023', 1, 2, '2-822 - Ornamental Metal Fences and Gates', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '28.5.2022', 2, 1, '4 - Masonry', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '8.2.2022', 2, 1, '11-070 - Instrumental Equipment', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '30.8.2022', 2, 1, '2-625 - Retaining Wall Drainage Piping', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '10.8.2022', 2, 1, '10-900 - Wardrobe and Closet Specialties', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '19.10.2022', 2, 1, '1-002 - Instructions', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '25.4.2022', 2, 1, '11-780 - Mortuary Equipment', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '5.6.2022', 2, 1, '16-300 - Transmission and Distribution', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '19.7.2022', 2, 1, '9-680 - Carpet', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '10.2.2022', 2, 1, '8-200 - Wood and Plastic Doors', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '12.8.2022', 2, 1, '2-782 - Brick Pavers', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '14.7.2022', 2, 1, '15-200 - Process Piping', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '19.4.2022', 2, 1, '1-903 - Hazardous Materials Abatement', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '22.10.2022', 2, 1, '11-650 - Planetarium Equipment', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '15.11.2022', 2, 1, '13-080 - Sound, Vibration, and Seismic Control', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '2.4.2022', 2, 1, '13-030 - Special Purpose Rooms', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '9.1.2023', 2, 1, '1-712 - Local Conditions', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '13.10.2022', 2, 1, '4-900 - Masonry Restoration and Cleaning', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '30.6.2022', 2, 1, '2-790 - Athletic Surfacing', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '6.2.2023', 2, 1, '11-080 - Registration Equipment', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '5.3.2023', 2, 1, '3-320 - Slab Foundations', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '16.10.2022', 2, 1, '7-600 - Flashing and Sheet Metal', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '6.5.2022', 2, 1, '5-050 - Basic Metal Materials and Methods', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '9.4.2023', 2, 1, '5-800 - Expansion Control', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '24.12.2022', 2, 1, '16-050 - Basic Electrical Materials and Methods', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '27.9.2022', 2, 1, '13-190 - Site-Constructed Incinerators', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '26.2.2023', 2, 1, '14-900 - Transportation', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '5.9.2022', 2, 1, '6-200 - Finish Carpentry', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '4.4.2022', 2, 1, '8-050 - Basic Door and Window Materials and Methods', 'SENT', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '17.10.2022', 2, 1, '14-100 - Dumbwaiters', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '13.1.2022', 2, 1, '1-903 - Hazardous Materials Abatement', 'READ', 1);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '15.4.2022', 1, 4, '1-002 - Instructions', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '16.2.2023', 1, 4, '15-500 - Heat-Generation Equipment', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '13.10.2022', 1, 4, '10-500 - Lockers', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '30.8.2022', 1, 4, '1-530 - Temporary Construction', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '4.4.2022', 1, 4, '13-230 - Digester Covers and Appurtenances', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '1.6.2022', 1, 4, '8-700 - Hardware', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '6.11.2022', 1, 4, '13-170 - Tubs and Pools', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '15.10.2022', 1, 4, '13-150 - Swimming Pools', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '3.4.2023', 1, 4, '15-900 - HVAC Instruments and Controls', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '9.3.2022', 1, 4, '16 - Electrical', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '22.5.2022', 1, 4, '10-200 - Louvers and Vents', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '13.8.2022', 1, 4, '5-700 - Ornamental Metal', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '16.9.2022', 1, 4, '12-800 - Interior Plants and Planters', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '20.12.2022', 1, 4, '11-500 - Industrial and Process Equipment', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '21.9.2022', 1, 4, '1-580 - Project Identification', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '23.3.2022', 1, 4, '11-700 - Medical Equipment', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '9.9.2022', 1, 4, '15-950 - Testing, Adjusting, and Balancing', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '27.2.2023', 1, 4, '16-400 - Low-Voltage Distribution', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '14.5.2022', 1, 4, '5-900 - Metal Restoration and Cleaning', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '14.1.2022', 1, 4, '2-500 - Utility Services', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '22.8.2022', 1, 4, '11-160 - Loading Dock Equipment', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '13.11.2022', 1, 4, '10-400 - Identification Devices', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '19.2.2022', 1, 4, '7-800 - Fire and Smoke Protection', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '30.4.2022', 1, 4, '3-500 - Cementitious Decks and Underlayments', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '3.11.2022', 1, 4, '13 - Special Construction', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '20.11.2022', 1, 4, '2-220 - Site Demolition', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '22.2.2023', 1, 4, '2-820 - Fences and Gates', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '22.11.2022', 1, 4, '10-200 - Louvers and Vents', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '11.1.2023', 1, 4, '4-200 - Masonry Units', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '12.5.2022', 1, 4, '9-700 - Wall Finishes', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '10.2.2023', 4, 1, '2-923 - Seeding and Soil Supplements', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '2.2.2023', 4, 1, '16 - Electrical', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '22.11.2022', 4, 1, '15-900 - HVAC Instruments and Controls', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '4.9.2022', 4, 1, '2-625 - Retaining Wall Drainage Piping', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '17.1.2022', 4, 1, '2-750 - Concrete Pads and Walks', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '10.10.2022', 4, 1, '13-175 - Ice Rinks', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '21.3.2022', 4, 1, '4-800 - Masonry Assemblies', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '3.4.2023', 4, 1, '13-090 - Radiation Protection', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '10.10.2022', 4, 1, '10-300 - Fireplaces and Stoves', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '5.8.2022', 4, 1, '1-700 - Execution Requirements', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '21.1.2023', 4, 1, '1-518 - Temporary Water', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '31.8.2022', 4, 1, '2-919 - Topsoil', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '16.9.2022', 4, 1, '9 - Finishes', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '5.3.2022', 4, 1, '8-400 - Entrances and Storefronts', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '24.7.2022', 4, 1, '3-310 - Expansion Joints', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '12.11.2022', 4, 1, '1-904 - Hazardous Materials Removal and Disposal', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '6.8.2022', 4, 1, '5-700 - Ornamental Metal', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '18.6.2022', 4, 1, '11-700 - Medical Equipment', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '16.8.2022', 4, 1, '11-160 - Loading Dock Equipment', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '19.6.2022', 4, 1, '4-200 - Masonry Units', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '28.1.2023', 4, 1, '11-090 - Checkroom Equipment', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '6.1.2023', 4, 1, '13-150 - Swimming Pools', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '10.7.2022', 4, 1, '10-600 - Partitions', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '11.8.2022', 4, 1, '10-240 - Grilles and Screens', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '6.9.2022', 4, 1, '8-700 - Hardware', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '4.8.2022', 4, 1, '7-900 - Joint Sealers', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '10.11.2022', 4, 1, '2-362 - Termite Control', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '17.5.2022', 4, 1, '10-450 - Pedestrian Control Devices', 'SENT', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '30.6.2022', 4, 1, '2-230 - Site Clearing', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '2.7.2022', 4, 1, '7-100 - Damproofing and Waterproofing', 'READ', 2);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '13.6.2022', 2, 3, '1-520 - Construction Facilities', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '9.6.2022', 2, 3, '3-300 - Footings', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '28.1.2022', 2, 3, '10-240 - Grilles and Screens', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '9.7.2022', 2, 3, '11-700 - Medical Equipment', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '13.10.2022', 2, 3, '2-310 - Grading', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '9.9.2022', 2, 3, '10-800 - Toilet, Bath, and Laundry Specialties', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '8.10.2022', 2, 3, '9-680 - Carpet', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '30.8.2022', 2, 3, '4-400 - Stone', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '28.7.2022', 2, 3, '2-825 - Wood Fences and Gates', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '25.8.2022', 2, 3, '12-400 - Furnishings and Accessories', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '13.9.2022', 2, 3, '9-250 - Gypsum Wallboard', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '14.3.2022', 2, 3, '13-120 - Pre-Engineered Structures', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '20.5.2022', 2, 3, '11-130 - Audio-Visual Equipment', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '2.2.2023', 2, 3, '11-080 - Registration Equipment', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '18.9.2022', 2, 3, '3-310 - Expansion Joints', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '28.4.2022', 2, 3, '2-362 - Termite Control', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '4.6.2022', 2, 3, '1-010 - Project Manager', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '13.3.2022', 2, 3, '15-950 - Testing, Adjusting, and Balancing', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '26.3.2022', 2, 3, '9-800 - Acoustical Treatment', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '6.4.2022', 2, 3, '9-600 - Flooring', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '25.11.2022', 2, 3, '2-784 - Stone Unit Pavers', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '23.2.2022', 2, 3, '10-450 - Pedestrian Control Devices', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '5.4.2023', 2, 3, '3-350 - Concrete Finishing', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '28.8.2022', 2, 3, '11-190 - Detention Equipment', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '27.12.2022', 2, 3, '12-700 - Systems Furniture', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '29.7.2022', 2, 3, '3-000 - General', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '1.8.2022', 2, 3, '1-013 - Project Coordinator', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '26.8.2022', 2, 3, '8-500 - Windows', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '7.3.2023', 2, 3, '3-100 - Concrete Reinforcement', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '15.1.2023', 2, 3, '1-542 - Construction Scaffolding and Platforms', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '21.1.2022', 3, 2, '11-160 - Loading Dock Equipment', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '23.7.2022', 3, 2, '15-200 - Process Piping', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '10.3.2023', 3, 2, '10-340 - Manufactured Exterior Specialties', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '26.4.2022', 3, 2, '11-700 - Medical Equipment', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '17.3.2023', 3, 2, '2-850 - Bridges/Footbridges', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '2.4.2023', 3, 2, '15-200 - Process Piping', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '16.11.2022', 3, 2, '1-011 - Project Engineer', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '22.10.2022', 3, 2, '2-783 - Interlocking Concrete Unit Paving', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '16.6.2022', 3, 2, '11-070 - Instrumental Equipment', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '21.1.2023', 3, 2, '1-570 - Temporary Controls', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '13.11.2022', 3, 2, '2-311 - Final Grading', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '7.1.2023', 3, 2, '2-830 - Retaining Walls', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '9.7.2022', 3, 2, '12-900 - Furnishings Restoration and Repair', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '15.11.2022', 3, 2, '15-600 - Refrigeration Equipment', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '15.3.2023', 3, 2, '11-060 - Theater and Stage Equipment', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '28.6.2022', 3, 2, '14-500 - Material Handling', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '31.10.2022', 3, 2, '10-800 - Toilet, Bath, and Laundry Specialties', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '14.5.2022', 3, 2, '1-514 - Temporary Heating, Cooling and Ventilation', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '21.11.2022', 3, 2, '2-930 - Exterior Plants', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '22.3.2022', 3, 2, '1-013 - Project Coordinator', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '30.9.2022', 3, 2, '13-550 - Transportation Control Instrumentation', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '1.2.2023', 3, 2, '1-514 - Temporary Heating, Cooling and Ventilation', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '20.2.2023', 3, 2, '13-550 - Transportation Control Instrumentation', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '18.2.2023', 3, 2, '13-150 - Swimming Pools', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '26.2.2022', 3, 2, '1-518 - Temporary Water', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '21.2.2022', 3, 2, '7-100 - Damproofing and Waterproofing', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '21.12.2022', 3, 2, '7-600 - Flashing and Sheet Metal', 'READ', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '18.1.2022', 3, 2, '9-400 - Terrazzo', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '4.2.2023', 3, 2, '3-100 - Concrete Reinforcement', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '29.6.2022', 3, 2, '7-100 - Damproofing and Waterproofing', 'SENT', 3);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '6.4.2022', 3, 4, '15-950 - Testing, Adjusting, and Balancing', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '6.1.2023', 3, 4, '3-310 - Expansion Joints', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '3.6.2022', 3, 4, '2-813 - Lawn Sprinkling and Irrigation', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '2.9.2022', 3, 4, '13-030 - Special Purpose Rooms', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '12.11.2022', 3, 4, '11-600 - Laboratory Equipment', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '10.3.2022', 3, 4, '11-680 - Office Equipment', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '13.7.2022', 3, 4, '9-600 - Flooring', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '29.6.2022', 3, 4, '1-002 - Instructions', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '7.8.2022', 3, 4, '3-310 - Expansion Joints', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '12.8.2022', 3, 4, '11-100 - Mercantile Equipment', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '7.1.2023', 3, 4, '4-200 - Masonry Units', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '19.7.2022', 3, 4, '11-080 - Registration Equipment', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '9.11.2022', 3, 4, '14 - Conveying Systems', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '6.11.2022', 3, 4, '10-530 - Protective Covers', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '7.4.2022', 3, 4, '11-120 - Vending Equipment', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '22.9.2022', 3, 4, '2-850 - Bridges/Footbridges', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '15.12.2022', 3, 4, '1-740 - Cleaning', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '11.11.2022', 3, 4, '2-830 - Retaining Walls', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '1.6.2022', 3, 4, '2-740 - Flexible Pavement Asphalt Pavement', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '20.9.2022', 3, 4, '4-700 - Simulated Masonry', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '6.3.2022', 3, 4, '2-923 - Seeding and Soil Supplements', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '18.6.2022', 3, 4, '3-400 - Precast Concrete', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '8.10.2022', 3, 4, '14-200 - Elevators', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '22.3.2023', 3, 4, '6-400 - Architectural Woodwork', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '6.1.2023', 3, 4, '5-200 - Metal Joists', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '29.5.2022', 3, 4, '11-070 - Instrumental Equipment', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '30.12.2022', 3, 4, '8-800 - Glazing', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '17.1.2022', 3, 4, '11-870 - Agricultural Equipment', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '14.12.2022', 3, 4, '11-480 - Athletic, Recreational, and Therapeutic Equipment', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '6.3.2023', 3, 4, '2-621 - Foundatation Drainage Piping', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '31.3.2022', 4, 3, '2-813 - Lawn Sprinkling and Irrigation', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '26.10.2022', 4, 3, '1-903 - Hazardous Materials Abatement', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '30.10.2022', 4, 3, '10-880 - Scales', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '2.11.2022', 4, 3, '5-500 - Metal Fabrications', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '22.11.2022', 4, 3, '15-700 - Heating, Venting and Air Conditioning', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '29.7.2022', 4, 3, '16-050 - Basic Electrical Materials and Methods', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '11.2.2022', 4, 3, '13-240 - Oxygenation Systems', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '4.3.2023', 4, 3, '3-600 - Grouts', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '22.3.2022', 4, 3, '10-260 - Wall and Corner Guards', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '8.4.2022', 4, 3, '3-330 - Poured Concrete Basement Walls', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '7.9.2022', 4, 3, '2-300 - Earthwork', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '7.3.2023', 4, 3, '7-400 - Roofing and Siding Panels', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '9.12.2022', 4, 3, '13-190 - Site-Constructed Incinerators', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '8.7.2022', 4, 3, '9-500 - Ceilings', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '2.11.2022', 4, 3, '9-300 - Tile', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '23.3.2023', 4, 3, '4 - Masonry', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '14.5.2022', 4, 3, '13-230 - Digester Covers and Appurtenances', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '28.10.2022', 4, 3, '12-500 - Furniture', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '30.1.2022', 4, 3, '13-200 - Storage Tanks', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '18.8.2022', 4, 3, '2-362 - Termite Control', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '21.6.2022', 4, 3, '4-900 - Masonry Restoration and Cleaning', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '6.12.2022', 4, 3, '9-700 - Wall Finishes', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '6.2.2023', 4, 3, '8-200 - Wood and Plastic Doors', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '28.4.2022', 4, 3, '4-800 - Masonry Assemblies', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '21.3.2022', 4, 3, '16-200 - Electrical Power', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '8.10.2022', 4, 3, '13-160 - Aquariums', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (false, '11.2.2022', 4, 3, '9-700 - Wall Finishes', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '14.7.2022', 4, 3, '17 - Markup and Contingency', 'SENT', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '1.12.2022', 4, 3, '2-740 - Flexible Pavement Asphalt Pavement', 'READ', 4);
insert into messages (is_deleted, time, author_id, recipient_id, message_text, status, dialog_id) values (true, '28.9.2022', 4, 3, '3-000 - General', 'SENT', 4);

insert into account_dialogs (dialog_id, account_id, recipient_id) values (1, 1, 2);
insert into account_dialogs (dialog_id, account_id, recipient_id) values (1, 2, 1);
insert into account_dialogs (dialog_id, account_id, recipient_id) values (2, 1, 4);
insert into account_dialogs (dialog_id, account_id, recipient_id) values (2, 4, 1);
insert into account_dialogs (dialog_id, account_id, recipient_id) values (3, 2, 3);
insert into account_dialogs (dialog_id, account_id, recipient_id) values (3, 3, 2);
insert into account_dialogs (dialog_id, account_id, recipient_id) values (4, 4, 3);
insert into account_dialogs (dialog_id, account_id, recipient_id) values (4, 3, 4);
COMMIT;
